// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QualityDoc.Data;

#nullable disable

namespace QualityDoc.Migrations.Core
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260608172112_AutorizadorRol")]
    partial class AutorizadorRol
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QualityDoc.Models.Domain.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("QualityDoc.Models.Domain.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("QualityDoc.Models.Domain.DocumentoVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComentarioRevision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("EsVigente")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("FueAprobada")
                        .HasColumnType("bit");

                    b.Property<string>("HashSha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MetadatosJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreArchivo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("RevisadoEn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RevisadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int>("SubidoPorId")
                        .HasColumnType("int");

                    b.Property<long?>("TamanioBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TextoExtracto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoArchivo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoRechazo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("VersionMayor")
                        .HasColumnType("int");

                    b.Property<int>("VersionMenor")
                        .HasColumnType("int");

                    b.Property<int>("VersionPatch")
                        .HasColumnType("int");

                    b.Property<string>("VersionTag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId")
                        .IsUnique()
                        .HasDatabaseName("UX_Versiones_UnaVigente")
                        .HasFilter("[EsVigente] = 1");

                    b.HasIndex("RevisadoPorId");

                    b.HasIndex("SubidoPorId");

                    b.HasIndex("EmpresaId", "Estado");

                    b.ToTable("DocumentoVersiones");
                });

            modelBuilder.Entity("QualityDoc.Models.Domain.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("QualityDoc.Models.Domain.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nivel = 0,
                            Nombre = "SUPERADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Nivel = 1,
                            Nombre = "ADMIN"
                        },
                        new
                        {
                            Id = 3,
                            Nivel = 3,
                            Nombre = "REVISOR"
                        },
                        new
                        {
                            Id = 4,
                            Nivel = 4,
                            Nombre = "CREADOR"
                        },
                        new
                        {
                            Id = 5,
                            Nivel = 5,
                            Nombre = "LECTOR"
                        },
                        new
                        {
                            Id = 6,
                            Nivel = 2,
                            Nombre = "AUTORIZADOR"
                        });
                });

            modelBuilder.Entity("QualityDoc.Models.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("QualityDoc.Models.Domain.Area", b =>
                {
                    b.HasOne("QualityDoc.Models.Domain.Empresa", "Empresa")
                        .WithMany("Areas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("QualityDoc.Models.Domain.Documento", b =>
                {
                    b.HasOne("QualityDoc.Models.Domain.Area", "Area")
                        .WithMany("Documentos")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QualityDoc.Models.Domain.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QualityDoc.Models.Domain.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("CreadoPor");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("QualityDoc.Models.Domain.DocumentoVersion", b =>
                {
                    b.HasOne("QualityDoc.Models.Domain.Documento", "Documento")
                        .WithMany("Versiones")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QualityDoc.Models.Domain.Usuario", "RevisadoPor")
                        .WithMany()
                        .HasForeignKey("RevisadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QualityDoc.Models.Domain.Usuario", "SubidoPor")
                        .WithMany()
                        .HasForeignKey("SubidoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("RevisadoPor");

                    b.Navigation("SubidoPor");
                });

            modelBuilder.Entity("QualityDoc.Models.Domain.Usuario", b =>
                {
                    b.HasOne("QualityDoc.Models.Domain.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QualityDoc.Models.Domain.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QualityDoc.Models.Domain.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Empresa");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("QualityDoc.Models.Domain.Area", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("QualityDoc.Models.Domain.Documento", b =>
                {
                    b.Navigation("Versiones");
                });

            modelBuilder.Entity("QualityDoc.Models.Domain.Empresa", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("QualityDoc.Models.Domain.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
